#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Tue Oct 21 19:54:01 2025

add_design "E:/Odyssey_proj/source/source/adc_capture_dual.v"
add_design "E:/Odyssey_proj/source/source/dpram_1024x16.v"
add_design "E:/Odyssey_proj/source/source/dual_channel_fft_controller.v"
add_design "E:/Odyssey_proj/source/source/fifo_async.v"
add_design "E:/Odyssey_proj/source/source/hdmi_display_ctrl.v"
add_design "E:/Odyssey_proj/source/source/hdmi_tx.v"
add_design "E:/Odyssey_proj/source/source/key_debounce.v"
add_design "E:/Odyssey_proj/source/source/reset_sync.v"
add_design "E:/Odyssey_proj/source/source/signal_analyzer_top.v"
add_design "E:/Odyssey_proj/source/source/signal_parameter_measure.v"
add_design "E:/Odyssey_proj/source/source/spectrum_magnitude_calc.v"
add_design "E:/Odyssey_proj/source/source/uart_tx.v"
add_design "E:/Odyssey_proj/source/src/iic_dri.v"
add_design "E:/Odyssey_proj/source/src/ms7210_ctl.v"
add_design "E:/Odyssey_proj/source/dpram/dpram.idf"
add_design "E:/Odyssey_proj/source/fft_1024/fft_1024.idf"
add_design "E:/Odyssey_proj/source/fifo_async_ip/fifo_async_ip.idf"
add_design "E:/Odyssey_proj/source/pll_hdmi/pll_hdmi.idf"
add_design "E:/Odyssey_proj/source/pll_sys/pll_sys.idf"
add_constraint "E:/Odyssey_proj/source/source/signal_analyzer.fdc"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module signal_analyzer_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
