# ----------------------------------------
# Created on: Sun Oct 26 14:46:27 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog -work work   \
"E:/Odyssey_proj/source/source/adc_capture_dual.v" \
"E:/Odyssey_proj/source/source/dual_channel_fft_controller.v" \
"E:/Odyssey_proj/source/source/fifo_async.v" \
"E:/Odyssey_proj/source/source/hdmi_display_ctrl.v" \
"E:/Odyssey_proj/source/source/hdmi_tx.v" \
"E:/Odyssey_proj/source/source/key_debounce.v" \
"E:/Odyssey_proj/source/source/reset_sync.v" \
"E:/Odyssey_proj/source/source/signal_analyzer_top.v" \
"E:/Odyssey_proj/source/source/signal_parameter_measure.v" \
"E:/Odyssey_proj/source/source/spectrum_magnitude_calc.v" \
"E:/Odyssey_proj/source/source/uart_tx.v" \
"E:/Odyssey_proj/source/source/char_rom_16x32.v" \
"E:/Odyssey_proj/source/source/phase_diff_calc.v" \
"E:/Odyssey_proj/source/source/auto_test.v" \
"E:/Odyssey_proj/source/source/iic_dri.v" \
"E:/Odyssey_proj/source/source/ms7210_ctl.v" \
"E:/Odyssey_proj/source/source/dpram_8192x11.v" \
"E:/Odyssey_proj/source/source/weak_signal_detector.v" \
"E:/Odyssey_proj/source/source/lock_in_amplifier.v" \
"E:/Odyssey_proj/source/source/ai_signal_recognizer.v" \
"E:/Odyssey_proj/source/source/waveform_classifier.v" \
"E:/Odyssey_proj/source/source/waveform_feature_extractor.v" \
"E:/Odyssey_proj/source/pll_hdmi/pll_hdmi.v" \
"E:/Odyssey_proj/source/pll_sys/pll_sys.v" \
"E:/Odyssey_proj/ipcore/fft_8192/fft_8192.v" \
"E:/Odyssey_proj/ipcore/fft_8192/rtl/synplify/ipsxb_fft_core_v1_0_vpAll.vp" \
"E:/Odyssey_proj/ipcore/fft_8192/rtl/distram_sreg/ipsxe_fft_distram_sreg.v" \
"E:/Odyssey_proj/ipcore/fft_8192/rtl/distram_sreg/rtl/ipsxe_fft_distributed_shiftregister_v1_3.v" \
"E:/Odyssey_proj/ipcore/fft_8192/rtl/distram_sreg/rtl/ipsxe_fft_distributed_sdpram_v1_2.v" \
"E:/Odyssey_proj/ipcore/fft_8192/rtl/distram_sdpram/ipsxe_fft_distram_sdpram.v" \
"E:/Odyssey_proj/source/DPRAM_8192x11/rtl/ipml_dpram_v1_8_DPRAM_8192x11.v" \
"E:/Odyssey_proj/source/DPRAM_8192x11/DPRAM_8192x11.v" \
"E:/Odyssey_proj/source/FIFO_ASYNC_8192x11/rtl/ipml_fifo_ctrl_v1_4_FIFO_ASYNC_8192x11.v" \
"E:/Odyssey_proj/source/FIFO_ASYNC_8192x11/rtl/ipml_sdpram_v1_9_FIFO_ASYNC_8192x11.v" \
"E:/Odyssey_proj/source/FIFO_ASYNC_8192x11/rtl/ipml_fifo_v1_9_FIFO_ASYNC_8192x11.v" \
"E:/Odyssey_proj/source/FIFO_ASYNC_8192x11/FIFO_ASYNC_8192x11.v" \
"E:/Odyssey_proj/source/source/ai_recognizer_testbench.v" 

# ----------------------------------------
