# ----------------------------------------
# Created on: Sun Oct 26 14:46:38 2025
# Auto generated by Pango
# ----------------------------------------

vsim  -voptargs="+acc" -L work ai_recognizer_testbench
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
