#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
字符映射ROM生成脚本
功能: 为HDMI显示生成字符位置到ASCII码的映射表
输出: COE格式文件（紫光同创ROM IP核初始化文件）

ROM布局:
- 地址0-99:   Y轴标度文本 ("100%", "75%", "50%", "25%", "0%")
- 地址100-299: X轴标度文本 (频域/时域标签)
- 地址300-499: AI识别区域文本 ("CH1:", "Sine", "CH2:", etc.)
- 地址500-999: 参数显示区域文本 ("CH1 Freq:", "CH2 Ampl:", etc.)
"""

def generate_char_map_rom():
    # 初始化ROM数组（默认空格ASCII 32）
    ROM_SIZE = 1024
    rom_data = [32] * ROM_SIZE
    
    print("=" * 60)
    print("字符映射ROM生成器")
    print("=" * 60)
    
    # ========== Y轴标度区域 (地址0-99) ==========
    print("\n[1/4] 生成Y轴标度映射...")
    y_axis_labels = [
        (0, "100"),   # Y=75位置
        (20, "75"),   # Y=262位置
        (40, "50"),   # Y=450位置
        (60, "25"),   # Y=637位置
        (80, "0")     # Y=825位置
    ]
    
    for addr_offset, label in y_axis_labels:
        for i, char in enumerate(label):
            rom_data[addr_offset + i] = ord(char)
        print(f"  地址{addr_offset:3d}-{addr_offset+len(label)-1:3d}: '{label}'")
    
    # ========== X轴标度区域 (地址100-299) ==========
    print("\n[2/4] 生成X轴标度映射...")
    
    # 频域标签 (地址100-199)
    x_axis_freq_labels = [
        (100, "0"),      # X=80
        (110, "3.5"),    # X=444
        (120, "7.0"),    # X=808
        (130, "10.5"),   # X=1172
        (140, "14.0"),   # X=1536
        (150, "17.5")    # X=1840
    ]
    
    for addr_offset, label in x_axis_freq_labels:
        for i, char in enumerate(label):
            rom_data[addr_offset + i] = ord(char)
        print(f"  [频域] 地址{addr_offset:3d}-{addr_offset+len(label)-1:3d}: '{label}' MHz")
    
    # 时域标签 (地址200-299)
    x_axis_time_labels = [
        (200, "0"),      # X=80
        (210, "47"),     # X=444
        (220, "93"),     # X=808
        (230, "140"),    # X=1172
        (240, "186"),    # X=1536
        (250, "234")     # X=1840
    ]
    
    for addr_offset, label in x_axis_time_labels:
        for i, char in enumerate(label):
            rom_data[addr_offset + i] = ord(char)
        print(f"  [时域] 地址{addr_offset:3d}-{addr_offset+len(label)-1:3d}: '{label}' us")
    
    # ========== AI识别区域 (地址300-499) ==========
    print("\n[3/4] 生成AI识别区域映射...")
    ai_labels = [
        (300, "CH1:"),
        (320, "Sine"),
        (340, "Square"),
        (360, "Triangle"),
        (380, "Sawtooth"),
        (400, "Noise"),
        (420, "CH2:"),
        (440, "Wave:"),
        (460, "Conf:")
    ]
    
    for addr_offset, label in ai_labels:
        for i, char in enumerate(label):
            rom_data[addr_offset + i] = ord(char)
        print(f"  地址{addr_offset:3d}-{addr_offset+len(label)-1:3d}: '{label}'")
    
    # ========== 参数显示区域 (地址500-999) ==========
    print("\n[4/4] 生成参数显示区域映射...")
    param_labels = [
        # 第一行: 频率 (Y=870-902)
        (500, "CH1"),
        (510, "Freq:"),
        (520, "Hz"),
        (550, "CH2"),
        (560, "Freq:"),
        (570, "Hz"),
        
        # 第二行: 幅度 (Y=905-937)
        (600, "CH1"),
        (610, "Ampl:"),
        (650, "CH2"),
        (660, "Ampl:"),
        
        # 第三行: 占空比 (Y=940-972)
        (700, "CH1"),
        (710, "Duty:"),
        (720, "%"),
        (750, "CH2"),
        (760, "Duty:"),
        (770, "%"),
        
        # 第四行: THD (Y=975-1007)
        (800, "CH1"),
        (810, "THD:"),
        (820, "%"),
        (850, "CH2"),
        (860, "THD:"),
        (870, "%"),
        
        # 第五行: 相位 (Y=1010-1042)
        (900, "Phase:"),
        (910, "deg")
    ]
    
    for addr_offset, label in param_labels:
        for i, char in enumerate(label):
            rom_data[addr_offset + i] = ord(char)
        print(f"  地址{addr_offset:3d}-{addr_offset+len(label)-1:3d}: '{label}'")
    
    # ========== 生成DAT文件（紫光同创格式）==========
    print("\n" + "=" * 60)
    print("生成DAT文件（紫光同创ROM格式）...")
    
    dat_filename = "char_map_rom.dat"
    with open(dat_filename, "w", encoding='utf-8') as f:
        # 紫光同创DAT格式：每行一个数据，十六进制格式
        for i in range(ROM_SIZE):
            f.write(f"{rom_data[i]:02X}\n")  # 十六进制，2位宽度，大写
    
    print(f"✅ 成功生成: {dat_filename}")
    print(f"   格式: 十六进制 (每行一个字节)")
    print(f"   ROM大小: {ROM_SIZE} 字节")
    print(f"   数据范围: ASCII 32-126 (0x20-0x7E)")
    
    # 同时生成MIF文件（备用格式）
    mif_filename = "char_map_rom.mif"
    with open(mif_filename, "w", encoding='utf-8') as f:
        f.write("-- Character Mapping ROM Initialization File\n")
        f.write("-- Auto-generated by generate_char_map_rom.py\n")
        f.write("-- Format: MIF (Memory Initialization File)\n")
        f.write(f"-- ROM Size: {ROM_SIZE} x 8 bits\n\n")
        
        f.write("WIDTH=8;\n")
        f.write(f"DEPTH={ROM_SIZE};\n\n")
        f.write("ADDRESS_RADIX=HEX;\n")
        f.write("DATA_RADIX=HEX;\n\n")
        f.write("CONTENT BEGIN\n")
        
        for i in range(ROM_SIZE):
            f.write(f"  {i:03X} : {rom_data[i]:02X};\n")
        
        f.write("END;\n")
    
    print(f"✅ 成功生成: {mif_filename} (备用格式)")
    
    # 统计非空格字符数
    non_space_count = sum(1 for x in rom_data if x != 32)
    print(f"   有效字符: {non_space_count} 个 ({non_space_count/ROM_SIZE*100:.1f}%)")
    
    # ========== 生成Verilog参数文件(可选) ==========
    param_filename = "char_map_addr_params.vh"
    with open(param_filename, "w", encoding='utf-8') as f:
        f.write("// Character Map ROM Address Parameters\n")
        f.write("// Auto-generated by generate_char_map_rom.py\n\n")
        
        f.write("// Y-axis labels\n")
        f.write("`define Y_AXIS_BASE_ADDR   10'd0\n\n")
        
        f.write("// X-axis labels (frequency domain)\n")
        f.write("`define X_AXIS_FREQ_BASE   10'd100\n\n")
        
        f.write("// X-axis labels (time domain)\n")
        f.write("`define X_AXIS_TIME_BASE   10'd200\n\n")
        
        f.write("// AI recognition area\n")
        f.write("`define AI_AREA_BASE       10'd300\n\n")
        
        f.write("// Parameter display area\n")
        f.write("`define PARAM_AREA_BASE    10'd500\n")
    
    print(f"✅ 成功生成: {param_filename}")
    print("\n" + "=" * 60)
    print("完成！下一步:")
    print("1. 在Pango Design Suite中创建DRM Based ROM IP核")
    print("2. 配置参数: Data Width=8, Addr Width=10, Depth=1024")
    print("3. 使用char_map_rom.dat作为初始化文件（或char_map_rom.mif）")
    print("4. 修改hdmi_display_ctrl.v实例化ROM IP核")
    print("=" * 60)

if __name__ == "__main__":
    generate_char_map_rom()
